# config.yaml
mqtt:
  broker_host: "localhost"
  broker_port: 1883
  topics:
    - "automotive/assembly/+/telemetry"
    - "factory/manufacturing/+/data"
  qos: 1

api:
  backend_url: "http://localhost:8080"
  endpoints:
    iot_data: "/api/iot-data"
    alerts: "/api/alerts"
  timeout: 5

influxdb:
  url: "http://localhost:8086"
  token: "automotive-assembly-token"
  org: "automotive"
  bucket: "assembly_data"
  enabled: true

processing:
  batch_size: 100
  flush_interval: 5  # seconds
  
logging:
  level: "INFO"
  file: "logs/data_collector.log"
  max_size: "10MB"
  backup_count: 5

stations:
  welding:
    - "WELDING_01"
  painting:
    - "PAINTING_02"
  assembly:
    - "ASSEMBLY_03"
  inspection:
    - "INSPECTION_04"
  stamping:
    - "STAMPING_05"