# config.yaml
mqtt:
  broker_host: "localhost"
  broker_port: 1883
  topics:
    # 스테이션별 센서 데이터 (15개 스테이션)
    - "factory/+/telemetry"
    - "factory/+/status" 
    - "factory/+/quality"
    - "factory/+/sensors"
    # 스테이션별 로봇 데이터
    - "factory/+/robots/telemetry"
    - "factory/+/robots/status"
    # 디지털 트윈 데이터
    - "factory/digital_twin/vehicle_tracking"
    - "factory/digital_twin/production_stats"
    # 생산라인 관리 데이터
    - "factory/production_line/status"
    # 공급망 데이터
    - "factory/supply_chain/status"
    # 전체 로봇 요약
    - "factory/robots/summary"
  qos: 1

api:
  backend_url: "http://localhost:8080"
  endpoints:
    iot_data: "/api/iot-data"
    kpi_data: "/api/kpi/data"
    vehicle_tracking: "/api/digital-twin/vehicles"
    robot_data: "/api/robots/data"
    production_status: "/api/production/status"
    supply_chain: "/api/supply-chain/status"
    alerts: "/api/alerts"
  timeout: 5
  retry_count: 3

influxdb:
  url: "http://localhost:8086"
  token: "automotive-assembly-token"
  org: "automotive"
  bucket: "assembly_data"
  enabled: true

processing:
  batch_size: 100
  flush_interval: 5  # seconds
  
logging:
  level: "INFO"
  file: "logs/data_collector.log"
  max_size: "10MB"
  backup_count: 5

stations:
  welding:
    - "WELDING_01"
  painting:
    - "PAINTING_02"
  assembly:
    - "ASSEMBLY_03"
  inspection:
    - "INSPECTION_04"
  stamping:
    - "STAMPING_05"