version: '3.8'

services:
  backend:
    build: 
      context: ./dashboard-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # PostgreSQL 연결 (ngrok 터널링)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://proxy151.r3proxy.com:34648/manufacturing_dashboard
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      
      # InfluxDB 연결 (ngrok 터널링)
      - INFLUXDB_URL=http://proxy151.r3proxy.com:34649
      - INFLUXDB_TOKEN=apiv3_cEbVg1AZ9vV8n6ldeFVBf_ZocFlxa170VAQ4Aq2uUHVUuE63fvdu5VSVhSiQvvPlCUVBSx4TD4b9fl_G334ISw
      - INFLUXDB_DATABASE=factory
    networks:
      - app-network

  frontend:
    build:
      context: ./dashboard-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      # API 서버 주소 설정
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge