version: '3.8'

services:
  backend:
    build: 
      context: ./dashboard_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - factory-network

  frontend:
    build:
      context: ./dashboard_frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - factory-network

networks:
  factory-network:
    driver: bridge