services:
  backend:
    build: 
      context: ./dashboard_backend  # 언더스코어 수정
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./dashboard_frontend  # 언더스코어 수정
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge