name: Deploy to AWS EC2 CodeDeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    - name: Create deployment package
      run: |
        # 배포에 필요한 파일들을 압축
        zip -r deployment-package.zip . -x "*.git*" "node_modules/*" "*.log"
    
    - name: Upload to S3
      run: |
        aws s3 cp deployment-package.zip s3://u1-factory-buckek/deployments/deployment-package-${{ github.sha }}.zip
    
    - name: Create CodeDeploy deployment
      run: |
        aws deploy create-deployment \
          --application-name factory-deploy-app \
          --deployment-group-name codedeploy-deployment-group \
          --s3-location bucket=u1-factory-buckek,key=deployments/deployment-package-${{ github.sha }}.zip,bundleType=zip \
          --deployment-config-name CodeDeployDefault.AllAtOnceBlueGreen \
          --description "Deployment from GitHub Actions - Commit: ${{ github.sha }}"
