name: Deploy to AWS EC2 via CodeDeploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 추가

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    - name: Verify deployment files
      run: |
        echo "=== 현재 디렉토리 구조 ==="
        ls -la
        
        echo "=== scripts 디렉토리 확인 ==="
        if [ -d "scripts" ]; then
          echo "✅ scripts 디렉토리 존재"
          ls -la scripts/
          echo "=== 스크립트 파일 권한 확인 ==="
          ls -la scripts/*.sh
        else
          echo "❌ scripts 디렉토리가 없습니다!"
          exit 1
        fi
        
        echo "=== appspec.yml 확인 ==="
        if [ -f "appspec.yml" ]; then
          echo "✅ appspec.yml 존재"
          cat appspec.yml
        else
          echo "❌ appspec.yml이 없습니다!"
          exit 1
        fi
    
    - name: Create deployment package
      run: |
        echo "=== 배포 패키지 생성 중 ==="
        # 배포에 필요한 파일들을 압축
        zip -r deployment-package.zip . -x "*.git*" "node_modules/*" "*.log" "venv/*"
        
        echo "=== 패키지 내용 확인 ==="
        unzip -l deployment-package.zip | grep -E "(appspec.yml|scripts/)"
    
    - name: Upload to S3
      run: |
        aws s3 cp deployment-package.zip s3://u1-factory-buckek/deployments/deployment-package-${{ github.sha }}.zip
    
    - name: Create CodeDeploy deployment
      run: |
        aws deploy create-deployment \
          --application-name factory-deploy-app \
          --deployment-group-name codedeploy-deployment-group \
          --s3-location bucket=u1-factory-buckek,key=deployments/deployment-package-${{ github.sha }}.zip,bundleType=zip \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --description "Deployment from GitHub Actions - Commit: ${{ github.sha }}"
